"""Platform-neutral production scheduler.

Generates scheduling configurations for cron, Windows Task Scheduler,
and cloud one-shot runners. Does NOT run as an always-on process.

Usage::

    python -m src.scheduler --format cron
    python -m src.scheduler --format windows
    python -m src.scheduler --format cloud
    python -m src.scheduler --install cron

Supports:
    - Morning scan (daily after overnight data refresh)
    - Pre-game scan (30 min before each game window)
    - Post-game calibration (nightly)
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import platform
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class ScheduleEntry:
    """A single scheduling entry."""
    name: str
    description: str
    cron_expression: str
    command: str
    working_directory: str
    enabled: bool = True

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "cron": self.cron_expression,
            "command": self.command,
            "working_directory": self.working_directory,
            "enabled": self.enabled,
        }


# ── Schedule definitions ───────────────────────────────────────────

def get_default_schedules() -> list[ScheduleEntry]:
    """Return the standard production schedule."""
    project_root = str(Path(__file__).resolve().parent.parent)
    python = sys.executable

    return [
        ScheduleEntry(
            name="morning_scan",
            description="Full morning pipeline: fetch, analyze, export, deliver, backup",
            cron_expression="0 9 * * *",  # 9:00 AM daily
            command=f'"{python}" -m src.production_jobs morning-run',
            working_directory=project_root,
        ),
        ScheduleEntry(
            name="pregame_scan",
            description="Pre-game scan 30 min before evening games",
            cron_expression="0 17 * * *",  # 5:00 PM (before 5:30 game windows)
            command=f'"{python}" -m src.production_jobs pregame-run',
            working_directory=project_root,
        ),
        ScheduleEntry(
            name="nightly_calibrate",
            description="Nightly calibration analysis and health check",
            cron_expression="0 23 * * *",  # 11:00 PM
            command=f'"{python}" -m src.production_jobs calibrate',
            working_directory=project_root,
        ),
        ScheduleEntry(
            name="weekly_backup",
            description="Weekly database backup with retention",
            cron_expression="0 3 * * 0",  # Sunday 3:00 AM
            command=f'"{python}" -m src.production_jobs backup',
            working_directory=project_root,
        ),
        ScheduleEntry(
            name="health_check",
            description="Daily health check (runs after morning scan)",
            cron_expression="30 9 * * *",  # 9:30 AM daily
            command=f'"{python}" -m src.production_jobs health-check',
            working_directory=project_root,
        ),
    ]


# ── Format generators ──────────────────────────────────────────────

def generate_cron(schedules: list[ScheduleEntry]) -> str:
    """Generate a crontab-compatible schedule."""
    lines = [
        "# MLB Sportsbook Analysis — Production Schedule",
        "# Generated by src/scheduler.py",
        "# Install: crontab < this_file",
        "#",
        "",
        "# Environment",
        "SHELL=/bin/bash",
        "MLB_LOG_LEVEL=INFO",
        "",
    ]
    for entry in schedules:
        if not entry.enabled:
            lines.append(f"# [DISABLED] {entry.name}")
            continue
        lines.append(f"# {entry.description}")
        lines.append(f"{entry.cron_expression} cd {entry.working_directory} && {entry.command}")
        lines.append("")

    return "\n".join(lines)


def generate_windows_task_scheduler(schedules: list[ScheduleEntry]) -> str:
    """Generate PowerShell commands for Windows Task Scheduler."""
    lines = [
        "# MLB Sportsbook Analysis — Windows Task Scheduler",
        "# Generated by src/scheduler.py",
        "# Run as Administrator in PowerShell",
        "#",
        "",
    ]

    for entry in schedules:
        if not entry.enabled:
            lines.append(f"# [DISABLED] {entry.name}")
            continue

        # Parse cron for time
        parts = entry.cron_expression.split()
        minute = parts[0] if len(parts) > 0 else "0"
        hour = parts[1] if len(parts) > 1 else "9"
        day_of_week = _cron_dow_to_windows(parts[4]) if len(parts) > 4 else "*"

        lines.append(f"# {entry.description}")
        lines.append(f'$Action = New-ScheduledTaskAction -Execute "cmd.exe" -Argument "/c cd /d {entry.working_directory} && {entry.command}"')
        lines.append(f'$Trigger = New-ScheduledTaskTrigger -Daily -At "{hour}:{minute.zfill(2)}"')
        if day_of_week != "*":
            lines = lines[:-1]
            lines.append(f'$Trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek {day_of_week} -At "{hour}:{minute.zfill(2)}"')
        lines.append(f'Register-ScheduledTask -TaskName "MLB_{entry.name}" -Action $Action -Trigger $Trigger -Description "{entry.description}" -Force')
        lines.append("")

    return "\n".join(lines)


def generate_cloud_config(schedules: list[ScheduleEntry]) -> dict[str, Any]:
    """Generate a cloud runner configuration (GitHub Actions, etc.)."""
    jobs = {}
    for entry in schedules:
        if not entry.enabled:
            continue
        jobs[entry.name] = {
            "description": entry.description,
            "cron": entry.cron_expression,
            "command": entry.command,
            "working_directory": entry.working_directory,
        }

    return {
        "version": "1.0",
        "description": "MLB Sportsbook Analysis — Cloud Schedule",
        "jobs": jobs,
    }


def generate_github_actions(schedules: list[ScheduleEntry]) -> str:
    """Generate a GitHub Actions workflow file."""
    lines = [
        "# MLB Sportsbook Analysis — GitHub Actions Schedule",
        "# Generated by src/scheduler.py",
        "name: Scheduled Jobs",
        "on:",
        "  schedule:",
    ]

    for entry in schedules:
        if not entry.enabled:
            continue
        lines.append(f"    - cron: '{entry.cron_expression}'")

    lines.extend([
        "  workflow_dispatch:",
        "jobs:",
        "",
    ])

    for entry in schedules:
        if not entry.enabled:
            continue
        safe_name = entry.name.replace("_", "-")
        lines.extend([
            f"  {safe_name}:",
            f"    runs-on: ubuntu-latest",
            f"    steps:",
            f"      - uses: actions/checkout@v4",
            f"      - uses: actions/setup-python@v5",
            f"        with:",
            f"          python-version: '3.12'",
            f"      - run: pip install -r requirements.txt",
            f"      - run: {entry.command}",
            f"        env:",
            f"          SPORTSODDS_API_KEY: ${{{{ secrets.SPORTSODDS_API_KEY }}}}",
            f"          MLB_DISCORD_WEBHOOKS: ${{{{ secrets.MLB_DISCORD_WEBHOOKS }}}}",
            f"          MLB_SPREADSHEET_ID: ${{{{ secrets.MLB_SPREADSHEET_ID }}}}",
            "",
        ])

    return "\n".join(lines)


# ── Install ────────────────────────────────────────────────────────

def install_cron(schedules: list[ScheduleEntry]) -> bool:
    """Install crontab entries on Linux/macOS."""
    if platform.system() == "Windows":
        logger.error("crontab not available on Windows. Use --format windows.")
        return False

    cron_content = generate_cron(schedules)
    try:
        proc = subprocess.run(
            ["crontab", "-"],
            input=cron_content,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if proc.returncode == 0:
            logger.info("Crontab installed successfully")
            return True
        else:
            logger.error("crontab failed: %s", proc.stderr)
            return False
    except FileNotFoundError:
        logger.error("crontab not found")
        return False


# ── Helpers ────────────────────────────────────────────────────────

def _cron_dow_to_windows(dow: str) -> str:
    """Convert cron day-of-week to Windows Task Scheduler format."""
    dow_map = {
        "0": "Sunday", "SUN": "Sunday",
        "1": "Monday", "MON": "Monday",
        "2": "Tuesday", "TUE": "Tuesday",
        "3": "Wednesday", "WED": "Wednesday",
        "4": "Thursday", "THU": "Thursday",
        "5": "Friday", "FRI": "Friday",
        "6": "Saturday", "SAT": "Saturday",
        "*": "*",
    }
    return dow_map.get(dow.upper(), "*")


# ── CLI ────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="scheduler",
        description="Generate production scheduling configurations",
    )
    parser.add_argument(
        "--format",
        choices=["cron", "windows", "cloud", "github-actions"],
        default="cron",
        help="Output format (default: cron)",
    )
    parser.add_argument(
        "--install",
        choices=["cron"],
        help="Install schedule directly (Linux/macOS only)",
    )
    parser.add_argument(
        "--output",
        help="Output file path (default: stdout)",
    )
    parser.add_argument(
        "--list", action="store_true", dest="list_schedules",
        help="List all schedule entries",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    schedules = get_default_schedules()

    if args.list_schedules:
        for entry in schedules:
            status = "enabled" if entry.enabled else "disabled"
            print(f"  {entry.name}: {entry.cron_expression} ({status}) — {entry.description}")
        return 0

    if args.install:
        if args.install == "cron":
            success = install_cron(schedules)
            return 0 if success else 1
        return 1

    if args.format == "cron":
        output = generate_cron(schedules)
    elif args.format == "windows":
        output = generate_windows_task_scheduler(schedules)
    elif args.format == "cloud":
        output = json.dumps(generate_cloud_config(schedules), indent=2)
    elif args.format == "github-actions":
        output = generate_github_actions(schedules)
    else:
        output = ""

    if args.output:
        Path(args.output).write_text(output)
        print(f"Schedule written to {args.output}")
    else:
        print(output)

    return 0


if __name__ == "__main__":
    sys.exit(main())
